### ISSUE TITLE
Fit image transform instead of crop

### ISSUE THREAD

**Issue by bilke** [markgoodyear/craft-retinafy#1]
I use retinafy with a **crop** image transform. In principal it works but the 2x image is generated by a **fit** transform.

**Comment by markgoodyear** [comment]
Hey @bilke, that makes sense. I should be checking which transform type the original is and using that. I'll try get that pushed up at some point today.

**Comment by bilke** [comment]
Cool, thanks!

**Comment by markgoodyear** [comment]
I've pushed an update now, v1.1.0 will use existing transform settings when using a transform. Let me know if you find any issues.
